TRUNCATE TABLE tareas RESTART IDENTITY CASCADE;
TRUNCATE TABLE horarios RESTART IDENTITY CASCADE;
TRUNCATE TABLE materias RESTART IDENTITY CASCADE;
TRUNCATE TABLE periodos RESTART IDENTITY CASCADE;
TRUNCATE TABLE usuarios RESTART IDENTITY CASCADE;